//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBs.Entyty
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyersInfo
    {
        public int PersonID { get; set; }
        public int CarID { get; set; }
        public int CityID { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual City City { get; set; }
        public virtual Person Person { get; set; }
    }
}
